name: Benchmark

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed
    branches: [ "main" ]

jobs:
  benchmark:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Run benchmarks
        run: |
          cd build/Release/tests/performance
          ./cperf_bench
