name: Benchmark

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  benchmark:
    needs: build
    runs-on: self-hosted
    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Run benchmarks
        run: |
          cd build/Release/tests/performance
          ./cperf_bench
